# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6d021461d350a1fd3dc77650c7901a46a8d607db83e0f435e714f500ab579f833c37375de454ae974ce6e8e297948508dc91885e3283213ab8eae9ace9e4d49

test:
  secret_key_base: 52aebd8e7c0b2c416ddf9921793c6ec66b42408695c31af05d195968548c9e76a186f46506a0c00b241e8bf1f34e542a6a9e159e99b8ab2dd002857dcf1a4e02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
